### ISSUE TITLE
Non-single primary key entity makes bundle crash

### ISSUE THREAD

**Issue by sescandell** [symfony2admingenerator/GeneratorBundle#161]
If in your project you are managing an entity with an association on a "composed primary key entity" (meaning its primary key is made of more than one field), the bundle crashes.

This is because of ~~https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Guesser/DoctrineORMFieldGuesser.php#L297~~.
Quick and dirty first fix: wrap this code by a try / catch.

**Comment by bobvandevijver** [comment]
Actual URL: https://github.com/symfony2admingenerator/GeneratorBundle/blob/e8d91de105863e28a478104131049590ed93303f/Guesser/DoctrineORMFieldGuesser.php#L297
