### ISSUE TITLE
Font Awesome Production Env

### ISSUE THREAD

**Issue by sebastianlp** [symfony2admingenerator/GeneratorBundle#168]
Hey.
When I switch to production environment I notice that the fa icons don't work.
Debuging the network loading I figured out that font-awesome files don't load correctly.

![screenshot from 2015-06-21 16 12 26](https://cloud.githubusercontent.com/assets/4922264/8273001/dfc8b0e0-1830-11e5-913d-8e723edae329.png)
- I configured the assetic to use UglifyCSS and UglifyJS.
- Installed the assets: 
  `php app/console admin:assets-install`
- Dump assets:
  `php app/console assetic:dump`

Both with `--env=prod and --env=dev`

Is there a config I missed here?

**Comment by pjam** [comment]
Hi @sebastianlp 

Did you solve this? My problem is the font source sans pro that is not used in production, only development, it could be related.

**Comment by sebastianlp** [comment]
Hey @pjam , unfortunately i didn't solve this in IMO a corrent way. 

This is what I've done

```yaml
# choose and uncomment only one
#    base_admin_template: AdmingeneratorGeneratorBundle::base.html.twig
#    base_admin_template: AdmingeneratorGeneratorBundle::base_uncompressed.html.twig
```

I had the problem with the first one, so when I use the base_uncompreseed.html.twig: problem solved!

**Comment by pjam** [comment]
Thanks for the quick reply.

Yes, I used the uncompressed layout before and didn't have this problem, but I wanted to take advantage of the assetic compression feature...

Thanks anyway

**Comment by sebastianlp** [comment]
I experienced this problem using the FA out of the admingenerator, but changing some configuration of assetic bundle I solved it, but not with the generator bundle :(

**Comment by pjam** [comment]
Strange, I never had any problem with FA in s2a, even when I switched to the compressed layout. Did you tried the cssrewrite filter and adding the admingeneratorbundle to the assetic configuration?

**Comment by sebastianlp** [comment]
Yes. When I use FA without the admingenerator, I've to use the cssrewrite filter. With admingenerator and compressed layout the fonts weren't loaded.

**Comment by loostro** [comment]
It seems its a problem with `cssrewrite` filter. I've recently also encountered it.
I did a quick solution by copying the fonts directory to `/web/assetic/css` (the css assets in `/web/assetic/css/compiled` looked for fonts awesome in `../fonts` relative path)
