### ISSUE TITLE
Probleme with command lines

### ISSUE THREAD

**Issue by rpostolov** [symfony2admingenerator/GeneratorBundle#185]
Hello everyone !

I'm on symfony 2.7 and i use GeneratorBundle.

I have some issue qith this bundle when i run the commande line 

```php app/console admin:generate-admin```

Here is the what it return me : 

```Generator to use (doctrine, doctrine_odm, propel)
  [0] doctrine
  [1] doctrine_odm
  [2] propel```

But when i select 0 or doctrine i have again and again the same proposition.

Here is my configuration in config.yml about orm

```       
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
       
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
       # naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        
        entity_managers:
            default:
                auto_mapping: true
                # New custom filter
                filters:
                    oneLocale:
                        class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                        enabled: true

#AdminGenerator
admingenerator_generator:
    generator_cache: global_cache.provider
    # choose  and enable at least one
    use_propel:           false
    use_doctrine_orm:     true
    use_doctrine_odm:     false
    overwrite_if_exists: false
    base_admin_template: AdmingeneratorGeneratorBundle::base_uncompressed.html.twig
    #dashboard_welcome_path: root vers le dashboard de l'admin
    #dashboard_route:     MyDashboard_path
    generator_cache: global_cache.provider
    login_route: fos_user_security_login
    logout_route: fos_user_security_logout
    twig:
        use_form_resources: true
        use_localized_date: false
        date_format: Y-m-d
        datetime_format: Y-m-d H:i:s
        localized_date_format: medium
        localized_datetime_format: medium
        number_format:
            decimal: 0
            decimal_point: .
            thousand_separator: ,
    templates_dirs: []
    stylesheets: []
    javascripts: []
  ```

Thanks for your help.

**Comment by rpostolov** [comment]
Hi !

GeneratorBundle works only with symfony 2.7.1 and not with 2.7.2

Bye.

**Comment by bobvandevijver** [comment]
Hi there, 

I'am afraid that this is not a problem with the admingenerator itself. We use the `Sensio\Bundle\GeneratorBundle\Command\Helper\QuestionHelper` to ask this question in the console, and we just use the return value (see line 43-54 [here](Sensio\Bundle\GeneratorBundle\Command\Helper\QuestionHelper")). 

Maybe you can do some debugging in the code to see what happens within the question helper? It might be related to the platform you use. I personally do not have the problems you describe.

**Comment by bobvandevijver** [comment]
Why did I not see your last comment? But okay, good to know. Another reason to always use the latest minor version :)

**Comment by sescandell** [comment]
@rpostolov are you sure this is coming from Symfony2.7.2 ?

Did you opened an issue about that symfony repository?

**Comment by bobvandevijver** [comment]
This might be connected to (this)[https://github.com/symfony/symfony/pull/15061], as they reverted a change introduced in 2.7. I've also had problems with that...

**Comment by rpostolov** [comment]
Hi !

@sescandell  Yes i'm sure because when i install symfony 2.7.1 instead of 2.7.2 it work fine.

But i didn't open an issue on symfony repository. I will immediatlly :)
