### ISSUE TITLE
select2 form widgets do not work in filter modal mode

### ISSUE THREAD

**Issue by tobias-93** [symfony2admingenerator/GeneratorBundle#196]
The forms input field cannot be selected due to the `tabindex=-1` setting in the modal div.
However, this setting makes sure the modal can be closed by pressing the escape button and is therefore included in the examples from bootstrap.
I can make a PR fixing this, but I'm not quite sure whether it's wanted behavior or that the widgets work.
Any opinion on this?

**Comment by tobias-93** [comment]
how to verify:

<pre>
params:
  fields:
     choicefield:
        filterType: s2a_select2_choice
        addFilterOptions:
          choices: [ a, b ]

builders:
  list:
    params:
       filtersMode: modal
       filters: [choicefield]
</pre>

**Comment by bobvandevijver** [comment]
Also see this stackoverflow post: http://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal. 

I do not really care about the esc button (that can be fixed using JS), but the functionality of the form widget is more important. 

@loostro @sescandell Opinions?

**Comment by sescandell** [comment]
Hi,
On the SO thread from @bobvandevijver some people talk about CSS solution or JS one.
@tobias-93 did you tried them?

If nothing works except removing the tab-index... remove it!

**Comment by tobias-93** [comment]
@sescandell no I didn't but I can try. I'll report back on this.
