### ISSUE TITLE
Are we ready to Symfony 3.0 ?

### ISSUE THREAD

**Issue by ksn135** [symfony2admingenerator/GeneratorBundle#220]
Hi there, everyone!
May be we should make a new branch  ?
What do you think about it ? Let's discuss it!

1. As far as I can see the most changes concerning form types
2. Several deprecation warnings in many parts of the code 
3. New configuration (yaml+php) as proposed by @loostro in #75 ?

More?

**Comment by bobvandevijver** [comment]
Hi @ksn135,

Our first priority would be to make a stable release of this bundle, with all correct documentation in place. Actually, I was planning to start on the documentation this holiday break. It is actually a reboot of #75, but that doesn't matter. 

I would also like to close as much issues as possible before making the bundle Symfony 3.0 complaint. Another thing that I worry about is the minimal PHP version: currently my development is on PHP 5.4, which does not support the `::class` which you desperately want for Symfony 3.0. 

Therefor: first fix as many bugs as possible here and create a decent documentation, tag that as stable for Symfony 2.x and then start on the Symfony 3.x branch.

**Comment by ksn135** [comment]
Well, I could help in closing tickets, but I'm not native English speaker so I can't help with docs.. (

**Comment by sescandell** [comment]
In PR #221 I removed as much as possible deprecated calls I've seen.
Remaining ones belong to Form and FormBuilder.

![image](https://cloud.githubusercontent.com/assets/1559970/12081385/191c1504-b277-11e5-9ec9-55e55a82b98c.png)

My plan is to finish this PR, then create a new one bumping the Symfony version to 2.8 and remove deprecations.

Let me know if it makes sense for you,

**Comment by loostro** [comment]
@sescandell good plan

**Comment by sescandell** [comment]
Yes we are! Well... once #224 is merged ;)
