### ISSUE TITLE
Variables don't get injected in Twig Extensions when generating bundle

### ISSUE THREAD

**Issue by tobias-93** [symfony2admingenerator/GeneratorBundle#226]
Unfortunately, I still experience problems related to #225. When operating, the `use_jms_security` parameter is injected fine. However, when generating, the parameter doesn't get injected due to the code in https://github.com/symfony2admingenerator/TwigGenerator/blob/master/src/TwigGenerator/Builder/BaseBuilder.php#L344.

I see three possible options for fixing this in this case:

1. The original solution in #225, so replacing all `echo_if_granted` by `echo_if('is_one_granted'`;
2. Injecting the variable into the function as a variable, thereby changing the function signature;
3. Finding out how to inject the variables when generating the bundle, but I'm not sure how to do that.

@sescandell what do you think?

**Comment by sescandell** [comment]
Hi @tobias-93 

Let me check that. I'll let you know quickly

**Comment by sescandell** [comment]
Ok found.

There was something strange that bother me: how could all other `twig functions` works whereas they are not in [this initialization](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Builder/BaseBuilder.php#L35). There was no reason `EchoExtension` doesn't know the `use_jms_security` (why `ConfigExtension` is so working well?).

And the thing is, the mistake __is__ the initialization. We just need to remove it. Twig extensions are copied from the "global" `twig` service [here](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Generator/DoctrineGenerator.php#L45), [here](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Generator/DoctrineODMGenerator.php#L43) and [here](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Generator/DoctrineODMGenerator.php#L43).

Tested on the demo project: working well :+1: Commit is coming (thanks for the report).

**Comment by tobias-93** [comment]
@sescandell Great, thanks so much for looking into it!
