### ISSUE TITLE
Error in Excel export implementation

### ISSUE THREAD

**Issue by calvera** [symfony2admingenerator/GeneratorBundle#229]
Hi all,

does anybody use Excel export of grid? I think there is bug in ExcelController generation. When I override some function in my ListController, I have to override the same in my ExcelController.

That's why I think admingenerated ExcelController has to extend my ListController and not admingenerated.

What do you think? Any other solution for this?

Thanks

-ks-

**Comment by bobvandevijver** [comment]
Hi @calvera, 

Actually, the ExcelController by default extends the ListController ([see here](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/templates/CommonAdmin/ExcelAction/ExcelBuilderAction.php.twig)). 

I just checked and you're right about that it does not extend your adjusted controller. However, you can not just extend your own ListController, as then you are missing the default ExcelActions. That means that we will have to use a clever extending mechanism, as we want to extend both classes (which is not possible in PHP). 

I will try to find a good solution for this...

**Comment by calvera** [comment]
Thanks for reply...

I meant that admingenerated ExcelController has to extend adjusted ListController... then it adds exceAction etc. Then I can adjust it in my ExcelController....

so:
my bundle's ExcelController extends admingenerated ExcelController which extends my bundle's ListController which extends admingenerated ListController...

There is no multiple extend...

**Comment by bobvandevijver** [comment]
That would indeed be the solution I had in mind, but I'm not sure if that is possible. Will have to check ;)

**Comment by calvera** [comment]
what about this?

```twig
class ExcelController extends \{{ namespace_prefix }}\{{ bundle_name }}\Controller\{{ builder.generator.baseGeneratorName }}\ListController
```
in ExcelBuilderAction

**Comment by sescandell** [comment]
Hi,

That makes me think about something: what if list builder is not in the generator file? Does the ExcelAction work?

**Comment by bobvandevijver** [comment]
@sescandell Just tested it, it does not work when the list builder is omitted from the generator file. I will include that in the new documentation. 

@calvera Your fix works, I will commit it.

**Comment by sescandell** [comment]
Thanks both of you :+1:

**Comment by Lionel09** [comment]
This fix creates a problem for an empty namespace, it's generate a ```class ExcelController extends \\{{ bundle_name }}\Controller\{{ builder.generator.baseGeneratorName }}\ListController```

Fatal error with prefix ```\\```

**Comment by bobvandevijver** [comment]
@sescandell Wouldn't we have this at more location than only here?

**Comment by sescandell** [comment]
Actually that's possible (look at my latests commits).

I have a project without namespace_prefix:

```yaml
generator: admingenerator.generator.doctrine
params:
    model: AppBundle\Entity\Project
    i18n_catalog: app
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~
```

I will do additional tests with that one to see if we missed some...

**Comment by bobvandevijver** [comment]
@sescandell Actually, you made a small mistake with the fix, so I fixed that :)

**Comment by sescandell** [comment]
:+1:
