### ISSUE TITLE
Skip warmup Method "ymlKey"

### ISSUE THREAD

**Issue by montabou** [symfony2admingenerator/GeneratorBundle#230]
I'm trying to upgrade from s2a old legacy to new unstable but when I modify some yml generator, I have this error
```
Skip warmup Method "ymlKey" for object "Admingenerator\GeneratorBundle\Builder\Doctrine\ShowBuilderTemplate" does not exist in "../CommonAdmin/tabs.php.twig" at line 14 
```
I've searched for ymlKey without success. How can I handle this error ?
I guess there should be a doc entry for that as it was not in old version ?

**Comment by bobvandevijver** [comment]
I've fixed your problem, it was a typo in a previous commit.

**Comment by montabou** [comment]
Arf, I did not think about that :-)
Thanks
