### ISSUE TITLE
Could not load type

### ISSUE THREAD

**Issue by montabou** [symfony2admingenerator/GeneratorBundle#231]
Using https://github.com/symfony2admingenerator/FormExtensionsBundle I've got an error when trying to load type using name. For example ```s2a_select2_entity```

The behaviour is the same with https://github.com/symfony2admingenerator/symfony2-admingenerator-demo-edition
If I replace ```Admingenerator\FormExtensionsBundle\Form\Type\Select2EntityType``` with ```s2a_select2_entity``` at
https://github.com/symfony2admingenerator/symfony2-admingenerator-demo-edition/blob/master/src/Admingenerator/DoctrineOrmDemoBundle/Resources/config/Post-generator.yml#L16
I've got the same error.

For now it works using the ```Admingenerator\FormExtensionsBundle\Form\Type\Select2EntityType``` but I was wondering if it a bug or a feature as it was convenient to use short name and works with old legacy admin generator.

**Comment by bobvandevijver** [comment]
The short `s2a_select2_entity` notation is deprecated since Symfony 2.8 and the FormExtensionsBundle was updated recently to remove those deprecation notices. If you want to use the short notation, you should stay with the old version of the FormExtensionsBundle.

**Comment by montabou** [comment]
My bad I did not know... Sorry for that.
Thanks again.
