### ISSUE TITLE
Optional routing update when using generate command

### ISSUE THREAD

**Issue by bobvandevijver** [symfony2admingenerator/GeneratorBundle#233]
In some cases the automatic routing update is not wanted (for example, you want the files in their bundle, and not in the top routing). Before, it was possible to disable that, this is however no longer the case.

**Comment by sescandell** [comment]
Is it because of #224 ?

**Comment by bobvandevijver** [comment]
I do not see any changes in #224 related to the command? But it might be, I guess I tested this against that branch.

**Comment by pjam** [comment]
Can't you make it so that we can choose what file to update/create?

**Comment by sescandell** [comment]
@bobvandevijver I've made a mistake in my comment, I was talking about PR #221

**Comment by bobvandevijver** [comment]
@sescandell Yes, it is indeed that one. So, I like the fact that we now only have a single command, but some of the configuration is missing. I think that @pjam has a good suggestion by the way.

**Comment by sescandell** [comment]
OK, I'll try to added that (or anyone else motivated? :))

**Comment by bobvandevijver** [comment]
Not really, I first want to finish the documentation ;)
