### ISSUE TITLE
TwigFilterException after lib update

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/GeneratorBundle#235]
Env: SF2.7 & Propel 1.6

I've got problems with GeneratorBundle after doing a ```composer update```

List of main updates:
```
  - Removing twig/twig (v1.23.1)
  - Installing twig/twig (v1.23.3)
    Downloading: 100%         

  - Removing symfony/symfony (v2.7.7)
  - Installing symfony/symfony (v2.7.9)
    Downloading: 100%         

  - Removing symfony2admingenerator/form-bundle (v1.2.1)
  - Installing symfony2admingenerator/form-bundle (v1.3.0)
    Downloading: 100%         

  - Updating symfony2admingenerator/form-extensions-bundle (dev-master fd2aa7b => v2.0-beta.21)
    Checking out 34ebe4fde3abdda3b5cff3377723b4968080f7da

  - Removing symfony2admingenerator/twig-generator (v1.1.4)
  - Installing symfony2admingenerator/twig-generator (v1.2.2)
    Downloading: 100%         
```

As you can see, I've put a specific tag for ```symfony2admingenerator/form-extensions-bundle``` as I had problem with master version with SF2.7.

GeneratorBundle stack trace exception:

```
Stack Trace
in app/cache/dev/classes.php at line 3461   -
public function addFilter($name, $filter = null)
{
if (!$name instanceof Twig_SimpleFilter && !($filter instanceof Twig_SimpleFilter || $filter instanceof Twig_FilterInterface)) {
throw new LogicException('A filter must be an instance of Twig_FilterInterface or Twig_SimpleFilter');
}
if ($name instanceof Twig_SimpleFilter) {
$filter = $name;
at Twig_Environment ->addFilter (object(Twig_Filter_Method)) 
in vendor/symfony2admingenerator/twig-generator/src/TwigGenerator/Builder/BaseBuilder.php at line 327   + 
at BaseBuilder ->loadTwigFilters (object(Twig_Environment)) 
in vendor/symfony2admingenerator/generator-bundle/Builder/BaseBuilder.php at line 113   + 
at BaseBuilder ->getTwigEnvironment () 
in vendor/symfony2admingenerator/twig-generator/src/TwigGenerator/Builder/BaseBuilder.php at line 262   + 
at BaseBuilder ->getCode () 
in vendor/symfony2admingenerator/twig-generator/src/TwigGenerator/Builder/BaseBuilder.php at line 253   + 
at BaseBuilder ->writeOnDisk ('/home/lionel/www/politizr.alpha/app/cache/dev/Admingenerated/PolitizrAdminBundle') 
in vendor/symfony2admingenerator/generator-bundle/Builder/BaseBuilder.php at line 96   + 
at BaseBuilder ->writeOnDisk ('/home/lionel/www/politizr.alpha/app/cache/dev/Admingenerated/PolitizrAdminBundle') 
in vendor/symfony2admingenerator/twig-generator/src/TwigGenerator/Builder/Generator.php at line 190   + 
at Generator ->writeOnDisk ('/home/lionel/www/politizr.alpha/app/cache/dev/Admingenerated/PolitizrAdminBundle') 
in vendor/symfony2admingenerator/generator-bundle/Generator/PropelGenerator.php at line 103   + 
at PropelGenerator ->doBuild () 
in vendor/symfony2admingenerator/generator-bundle/Generator/Generator.php at line 178   + 
at Generator ->build () 
in vendor/symfony2admingenerator/generator-bundle/EventListener/ControllerListener.php at line 59
```

What's going wrong?

**Comment by bobvandevijver** [comment]
Well, with a little bit of research I'm sure you could have worked this out yourself, but here it goes:

The  `Twig_Filter_Method` is deprecated since Twig 1.12. In the latest Twig version, @fabpot changed something that is BC-breaking with this deprecated functionality (see https://github.com/twigphp/Twig/commit/1918edefa937b81233087aa79297e54ea0462f9b#diff-5e190f538c5c328c7473a5cfd3b7cd95R760). This is as `Twig_Filter_Method` is not a `Twig_SimpleFilter`, but a `Twig_Filter`. You might want to notify them, but as it is deprecated, I do not think they will fix it. 

So, you have two options to fix this:
* Downgrade your Twig to 1.23.2, the conflicting commit does not seem to in there, or go down even further.
* Upgrade the admingenerater to at least  `v2.0-beta42`, there the usage of `Twig_Filter_Method` is removed. You will also want to have `v1.2.2` of the `TwigGenerator` bundle.

**Comment by Lionel09** [comment]
Thanks for helping!

> Upgrade the admingenerater to at least v2.0-beta42, there the usage of Twig_Filter_Method is removed. You will also want to have v1.2.2 of the TwigGenerator bundle.

When I've posted this problem, I had Generator-Bundle to v2.0-beta42 w. TwigGenerator bundle v1.2.2.

Now I upgrade to GeneratorBundle v2.0-beta43: I first had to upgrade sensio/generator-bundle to ~3.0 but I've got always the same error.

**Comment by bobvandevijver** [comment]
Maybe you've defined a custom Twig Filter? If so, check those. Might even not be related to the AdminGenerator, which just hits it as it loads the Twig environment.

**Comment by Lionel09** [comment]
I've already updated my custom twig filters to newest signature

Search in whole "src" & "vendor", and founded 2 in external lib:
- a filter in propel-bundle (```formatSQL```), used for debug toolbar > I will check with them
- a filter in form-extensions-bundle > seems that last version (with filter fix) is not compatible w. SF2.7 see https://github.com/symfony2admingenerator/FormExtensionsBundle/issues/55

**Comment by Lionel09** [comment]
I've updated Symfony to 2.8.2 and last "stable" for every others libs, including Twig. Everything works fine in the admingenerator (and in other parts of my app) except when I update ```symfony2admingenerator/twig-generator``` which throws the ```Twig_SimpleFilter``` Exception.

**Comment by bobvandevijver** [comment]
Well, as you can see in https://github.com/symfony2admingenerator/TwigGenerator/pull/3, there are ony `Twig_SimpleFilter` classes... Do you have a complete stack-trace? Try to dump the conflicting filter to see where it comes from (edit the source of the `AddFilter` call to include a dump of the filter).

**Comment by Lionel09** [comment]
Thanks for your patience @bobvandevijver 

The problem comes from the ```symfony2admingenerator/form-bundle``` which seems to not be up to date with the last release. This project was not included in my ```composer.json``` because it was automatically loaded with ```GeneratorBundle```, but the ```composer update``` process has not updated this one, so I add it to my ```composer.json``` now.
