### ISSUE TITLE
FormType (as a service) with constructor

### ISSUE THREAD

**Issue by montabou** [symfony2admingenerator/GeneratorBundle#236]
Using A2lix translation bundle, I've encountered:
```php
Catchable Fatal Error:
Argument 1 passed to A2lix\TranslationFormBundle\Form\Type\TranslationsType::__construct()
must be an instance of A2lix\TranslationFormBundle\Form\EventListener\TranslationsListener,
none given, Admingenerated/AdminBundle/Form/BaseVariationType/EditType.php on line 64
```
The generated line 64 looks like:
```php
    /**                                                                                                              
     * Get form type for translations field.                                                                         
     *                                                                                                               
     * @return string|FormTypeInterface Field form type.                                                             
     */                                                                                                              
    protected function getTypeTranslations()                                                                         
    {                                                                                                                
        return $this->inject(new \A2lix\TranslationFormBundle\Form\Type\TranslationsType());                         
    }  
```
I understand the problem and I'm wondering is GeneratorBundle is able to deal with form type defined as a service ?
http://symfony.com/doc/current/cookbook/form/create_custom_field_type.html#creating-your-field-type-as-a-service

**Comment by sescandell** [comment]
Hi @montabou ,

Do you have any `generator.yml` code to show us? I think it should work (not sure...)

When #224 is merged, everything should be okay (given that the `inject` method does not exist anymore).

**Comment by montabou** [comment]
My generator is very simple. Everything works just fine if I use the old syntax (with shortname a2lix_translations). The error occurs if I replace with new complete type.
If you think #224 will correct this issue, just wait and see :-)

**Comment by sescandell** [comment]
Yes, actually the "new" syntax (using FQCN) is not yet supported by the bundle. #224 should fix this (take care that #224 bump the sf version to 2.8 minimum).

**Comment by sescandell** [comment]
#224 is merged.

Let us know if it is working now.

If not, please, show us your generator file.

**Comment by montabou** [comment]
Thanks it works now !
