### ISSUE TITLE
Money show type not usable in show view 

### ISSUE THREAD

**Issue by bobvandevijver** [symfony2admingenerator/GeneratorBundle#238]
The [`money.php.twig`](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/templates/CommonAdmin/ListTemplate/Column/money.php.twig) template is currently not usable in the show view. This should be possible.

**Comment by loostro** [comment]
It could be moved to `Resources/templates/CommonAdmin`

**Comment by bobvandevijver** [comment]
When actually all types in the `CommonAdmin/ListTemplate/Column` directory are used in the show column template (see [here](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/templates/CommonAdmin/ShowTemplate/column.php.twig)). 

I was more thinking about adding it there, and adjusting it that it is not dependent on the formoptions, as it currently is.

**Comment by loostro** [comment]
Ok
