### ISSUE TITLE
Date: unable to transform value for property path

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/GeneratorBundle#242]
Env: SF2.8 + Generator v2.0.1

Exception throws in edit mode for date fields

```Unable to transform value for property path "created_at": Expected a \DateTime or \DateTimeInterface.```

The injected value is a string like '2016-02-01 15:20:27'.

My form types are formextensions ones, but same problem w. default Symfony core type.

```
    form_types:
        propel:
            TIMESTAMP:    Admingenerator\FormExtensionsBundle\Form\Type\DateTimePickerType
            BU_TIMESTAMP: Admingenerator\FormExtensionsBundle\Form\Type\DateTimePickerType
            DATE:         Admingenerator\FormExtensionsBundle\Form\Type\DateRangePickerType
            BU_DATE:      Admingenerator\FormExtensionsBundle\Form\Type\DatePickerType
```

**Comment by Lionel09** [comment]
see master branche in https://github.com/Lionel09/project-sf2.8

just after creating a new "Category" object, the exception is throwed in edition

**Comment by sescandell** [comment]
As far as I understand Propel, this is a Propel issue.

If you look at how propel handle dates, you can see the following code:

```php
    /**
     * Get the [optionally formatted] temporal [created_at] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getCreatedAt($format = 'Y-m-d H:i:s')
    {
        if ($this->created_at === null) {
            return null;
        }

        if ($this->created_at === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        }

        try {
            $dt = new DateTime($this->created_at);
        } catch (Exception $x) {
            throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        }

        if (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        }

        return $dt->format($format);

    }
```

You should have a look to Propel documentation or create your own getter and configure it as the getter in the generator (because, AFAIK, there is no way to say to Symfony: use the getCreatedAt with "null" parameter).

*edit*: looking by myself, if you can change it, simply put null as config value to the following parameter:

```yaml
propel:
    build_properties:
        propel.defaultTimeStampFormat: ~
```

I don't know what are consequences over your application.

**Comment by Lionel09** [comment]
Thanks a lot @sescandell I will look for Propel to fix this one

Do you know which evolution broke this old Propel behavior? Generator refactoring - or SF?

**Comment by sescandell** [comment]
Is this something that was working until now? Exactly with the same configuration (espacially the propel.defaultTimeStamFormat one)?

**Comment by Lionel09** [comment]
Yes it was working with the same config, I didn't change anything here (I've tried your tip about the "defaultTimeStampFormat" in the config, but it doesn't change anything).

To be exact, the propel bundle has recently slightly evolved with a 1.5 branch to be compatible with SF2.8; I've redo the test with the previous branch (1.4) in this "test project", and I've got the same error.

On the other hand, I've a big project running with sf2.8 & generator-beta42 & propel-bundle 1.4 running perfectly well!

**Comment by sescandell** [comment]
> (I've tried your tip about the "defaultTimeStampFormat" in the config, but it doesn't change anything).

Don't you forget to re-build the model after modifying the parameter using the `propel:model:build`?
I'm sure this is working:
![image](https://cloud.githubusercontent.com/assets/1559970/12859634/c0d7a7aa-cc57-11e5-8577-d79243d7b873.png)

I went through [differences between 2.0-beta42 and master](https://github.com/symfony2admingenerator/GeneratorBundle/compare/v2.0-beta42...master) and I don't see anything that could be linked to DateTime manipulation... To be honest, I don't have any idea for now why it is not working (except the `defaultTimeStampFormat` I'm talking about).

Could you share a repo with a working  case ? (even in beta42)

Thanks,

**Comment by Lionel09** [comment]
> Don't you forget

Shame on me, yes I do; and yes it works now...

Thanks a lot for your help @sescandell
