### ISSUE TITLE
Slashes are stripped where they should not be.

### ISSUE THREAD

**Issue by tobias-93** [symfony2admingenerator/GeneratorBundle#243]
The `stripslashes` in https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Twig/Extension/EchoExtension.php#L64 causes slashes to be stripped in strings where they should be kept (for instance in a string with apostrophes). This can cause a string to be terminated too early, causing syntax errors.
@sescandell any thoughts on a better way? This is too rigorous.

**Comment by sescandell** [comment]
Do you have any sample so we can add it to the tests?

Thanks,

**Comment by tobias-93** [comment]
<pre>
  params:
    fields:
      name:
        formOptions:
          label: "How 'ya doing?"
</pre>

This could be used in the `no_modifications` string to be tested.
Mark the double quotes versus the single quote.

**Comment by sescandell** [comment]
:+1:

**Comment by sescandell** [comment]
@tobias-93 Let me know if this is better now,

**Comment by tobias-93** [comment]
@sescandell Yes, thank you!

**Comment by sescandell** [comment]
Actually it's not OK, a commit is coming
