### ISSUE TITLE
KnpMenuBundle as optional/recommended dependency

### ISSUE THREAD

**Issue by bobvandevijver** [symfony2admingenerator/GeneratorBundle#245]
Currently, the KnpMenuBundle is an required dependency and even when you do not use it, you need to install and enable it due to the [service definition](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/config/services.xml#L85). 

However, you can use the bundle fine without this bundle. Therefor, I would like to propose to make it an optional dependency and to create the service definition such that it can be enabled if wanted. Any thoughts?

**Comment by sescandell** [comment]
You would also have to [update the template here](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/views/Sidebar/layout.html.twig#L14) if you do so.

Is there any situation you would don't want to use it?

**Comment by bobvandevijver** [comment]
I do not use most of the default templates, but I imagine there will be more occurrences, so that must be checked.

We do not use the menu bundle due to the fact we integrated the bundle in a much larger application, which does not use the KnpMenuBundle for its menu. Actually, we use a self-written menu generator and we define the menu completely in the routing files. But, we might be alone is this :)

**Comment by sescandell** [comment]
Well... maybe we could remove it from the bundle you're right, and just precise in a "cookbook" how to easily integrate KnpMenu in the bundle...

@loostro any insight?

**Comment by loostro** [comment]
I'm :+1: for removeing the dependency. A dashboard/links system is not the "core" of this bundle. The core of this bundle is generateing CRUD for models, and auto-generateing routes is what I still consider "core", but the menu system is purely optional. It should be described how to quickly setup basic menu system with KnpMenuBundle, but it's not mandatory to use it.

**Comment by bobvandevijver** [comment]
There already is some doc in the cookbook about the menu, but it is probably a little bit outdated (see #239). I will copy the current doc to the new documentation, but I will not adjust it yet as this should be inspected first.
