### ISSUE TITLE
EmbedType

### ISSUE THREAD

**Issue by sescandell** [symfony2admingenerator/GeneratorBundle#247]
I missunderstood requirements for embedTypes and didn't take enough care to previous implementation of this functionality. But PR #224 break this functionnality.

Before #224, we simply needed to create a generator file with only the "global" configuration.
Now, you need to create a full generator file with at least Edit and New builders. Doing that, corresponding controllers will be created too (that wasn't the case before the PR).

That should be fixed.

**Comment by sescandell** [comment]
Not an issue, actually, everything is working as before except that `embed_types` key word in generator is not required anymore.

**Comment by bobvandevijver** [comment]
@sescandell  I lost complete track on this functionality (and I do not use it I guess), maybe you can add  some documentation to the documentation PR?

**Comment by sescandell** [comment]
@bobvandevijver I'll do
