### ISSUE TITLE
How to / Dynamic form modifications in select dropdown

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/GeneratorBundle#256]
Env: SF2.8 / Propel 1.7 / Generator 2.0

I'm trying to update a dropdow list depending of the value of another one - like explained in http://symfony.com/doc/2.8/cookbook/form/dynamic_form_modification.html#cookbook-form-events-underlying-data - with a little XHR request which updates the second list with new values when the user select one in the first list.

This code was ok with previous AdminGenerator (v1), but now it breaks because of the bootstrap addons (```btn-group bootstrap-select form-control```). Actually, the values of the ```<select><option>``` are updated, but for sure not the boostrap code.

How can I do now? Can I force the use of "classical" select dropdown or have I to update bootstrap code with XHR too? other idea?

Thanks!

**Comment by calvera** [comment]
does this work?

http://stackoverflow.com/questions/23514318/bootstrap-select-reinitialize-on-dynamically-added-element

**Comment by Lionel09** [comment]
perfect, thanks a lot @calvera
