### ISSUE TITLE
Can't find app folder

### ISSUE THREAD

**Issue by 3Lies** [symfony2admingenerator/GeneratorBundle#258]
Please rewrite the install tutorial, i can't find app folder and the yaml file

Thank you!

**Comment by bobvandevijver** [comment]
The docs are currently being rewritten, check out the branch: [new-doc](https://github.com/symfony2admingenerator/GeneratorBundle/blob/new-doc/Resources/new-doc/documentation.md). Should cover the installation instructions. 

The app folder is off course on top of a fresh Symfony install.

**Comment by 3Lies** [comment]
thanks a lot!
