### ISSUE TITLE
PagerfantaBundle update breaks admingenerator pagination

### ISSUE THREAD

**Issue by bobvandevijver** [symfony2admingenerator/GeneratorBundle#266]
In [PagerfantaBundle#131](https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/pull/131) an update is created which by default omits the `page` URL param if the page is 1. This is apparently also correct according to the RFC, although it breaks our pagination. 

As we save the current page in the session, it is no longer possible to return to the first page of the list after you've visited another page (when using the paginator links, you can change a page=4 url manually to 1). We save the page in the session such that we can easily return to the same page after an specific action. 

I see four possible solutions:
1. Fix the Pagerfanta version on the old version
2. Make the Pagerfanta behavior configurable in the Pagerfanta bundle self, which can be easily done with a single parameter.
3. Adapt our [AdminGeneratorView](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Pagerfanta/View/AdmingeneratorView.php#L113) to overwrite the Pagerfanta behavior for this first page
4. Adapt our complete session model and update all URL used everywhere.

Option 1 & 4 are a no go in my opinion. I will try to push option 2 to the Pagerfanta bundle, but if it fails we probably use option 3.

**Comment by bobvandevijver** [comment]
I've created a PR at [PagerfantaBundle#140](https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/pull/140) to fix this, when merged we only need to add the param to our Pagerfanta call.

**Comment by sescandell** [comment]
:+1: thanks for the prevention

**Comment by bobvandevijver** [comment]
Well, it's merged. Now we just have to wait for a new release, so that I can update our composer file :)
