### ISSUE TITLE
Should we catch empty batch actions?

### ISSUE THREAD

**Issue by bobvandevijver** [symfony2admingenerator/GeneratorBundle#271]
Currently, when JS fails a button is displayed for the batch actions, which simply executes the selected action. 

However, when the 'Selected' is selected (so no action) and the button is clicked, the following error is thrown:
```
Undefined "attemptBatchNone" method. Does batch action "none" exist in your generator file?
```

This indicates that there is no server check for faulty requests here. We should probably check this in the controller and forward the user to the list page when this happens. 

Any opinions? @sescandell @loostro?

**Comment by sescandell** [comment]
I think there is two things here:

 - If "none" action is submitted, we should not send the request (I thought that was already the case...) : JS modification
 - IMO, if the action doesn't exist, we should simply return a 404

**Comment by bobvandevijver** [comment]
* Yes, the JS already prevents this (it even hides the button, it simply works on a change of the action). However, we should not rely on the JS working always, so there should also be server-side handling. The JS was not working correctly, that's why I found it ;)
* I agree on production, but not in debug mode. Maybe use the `kernel.debug` parameter to check for the correct response? Nevertheless, I am still convinced that handling the None and giving a simple message to the use is better than a hard 'Not found' page.

**Comment by sescandell** [comment]
You're right about debug mode. You should be able to use the `throw_exception` parameter instead of checking `kernel.debug`

**Comment by bobvandevijver** [comment]
Actually, I see that we do not use the `kernel.debug` parameter at the moment. I will suggest we automatically set the `throw_exceptions` to true when `kernel.debug` is true (which is actually already described as such in the docs). 

I will create a PR which handles the 'None' case and changes the current exception into not found when not in debug or throw_exceptions.

**Comment by bobvandevijver** [comment]
Actually, the `NotFoundHttpException` is thrown, which is not handled in a debug environment, but it is on a production environment. So no changes needed there.

**Comment by sescandell** [comment]
:+1:
