### ISSUE TITLE
Knp menu bundle.

### ISSUE THREAD

**Issue by yuriyzinchenko** [symfony2admingenerator/GeneratorBundle#278]
Hi, in 2.1.0 version knplabs/knp-menu-bundle is removed, but in GeneratorBundle/Resources/views/Sidebar/layout.html.twig:
```twig
    {% block sidebar_menu %}
        {% if admingenerator_config('knp_menu_alias') is not null %}
            {{ knp_menu_render(admingenerator_config('knp_menu_alias')) }}
        {% endif %}
    {% endblock sidebar_menu %}
```

Should I add knplabs/knp-menu-bundle to my composer.json or it is a mistake?
Thanks.

**Comment by tobias-93** [comment]
@yuriyzinchenko As described in the original discussion (#245), it is optional. If you want to use it, I would recommend you read the cookbook article on it (https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/doc/cookbook/knp-menu.md), but it is not necessary. You should not run into problems as long as you don't set the `knp_menu_alias`-config.

**Comment by bobvandevijver** [comment]
Also noted in the [upgrade notes](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/UPGRADE.MD).

**Comment by yuriyzinchenko** [comment]
Thanks.
