### ISSUE TITLE
MillwrightMenuBundle

### ISSUE THREAD

**Issue by yuriyzinchenko** [symfony2admingenerator/GeneratorBundle#280]
Hi, Do you plan to make integration with MillwrightMenuBundle?
Is it possible to integrate AdminGeneratorBundle with MillwrightMenuBundle now?

**Comment by bobvandevijver** [comment]
No, we do not plan to integrate another menu bundle in this bundle. We previously has the KnpMenuBundle integrated (which we actually removed), but the cookbook article about it should help you to integrate any other menu bundle.

Take a look at the [documentation], you should be able to find a lot in there(https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/doc/documentation.md)! :smiley:
