### ISSUE TITLE
Exclude fields from generation

### ISSUE THREAD

**Issue by yuriyzinchenko** [symfony2admingenerator/GeneratorBundle#281]
Does  AdmingeneratorBundle has an option that allows to exclude some fields from generated files for all entities(for each entity will be excellent)(e.g. createdAt, deletedAt, updatedAt etc...)?

**Comment by bobvandevijver** [comment]
@yuriyzinchenko No, we do not have an option to exclude fields. You can however select which fields you want to display for the list, filter, new, edit and Excel actions, which provides you with the same possibilities.
