### ISSUE TITLE
 Error parsing YAML, invalid file

### ISSUE THREAD

**Issue by wirtoo** [symfony2admingenerator/GeneratorBundle#282]
Hi! I've just installed it using [documentation](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/doc/install/base-installation.md) on symfony 2.8.4 and trying to run `php app/console cache:clear`.
Getting this:

`[Symfony\Component\Translation\Exception\InvalidResourceException]                                                                                
  Error parsing YAML, invalid file "/var/www/my_project/vendor/symfony2admingenerator/generator-bundle/Resources/translations/Admingenerator.fr.yml" `

` [Symfony\Component\Yaml\Exception\ParseException]                                                                                  
  A colon cannot be used in an unquoted mapping value at line 84 (near "notfound: Suppression impossible : l'élément est inconnu"). `

Am i doing something wrong, or that's an issue?
I've tried to do it on my project and on clean symfony (latest LTS - 2.8).
If any additional information needed - i'll provide it.
Thanks.

**Comment by sescandell** [comment]
Should be fixed thanks to https://github.com/symfony2admingenerator/GeneratorBundle/commit/b19495b4192dcea1e84a171d3426004e33c144f1

Could you please confirm? (using master branch)

**Comment by wirtoo** [comment]
yes, it works.
thanks a lot.
