### ISSUE TITLE
Override *.php.twig template  files.

### ISSUE THREAD

**Issue by yuriyzinchenko** [symfony2admingenerator/GeneratorBundle#286]
Hi, can i override *.php.twig file that generates base template? (e.g. Resources/templates/CommonAdmin/ListTemplate/scopes.php.twig)

**Comment by bobvandevijver** [comment]
Yes you can. Please take a look at the [documentation](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/doc/customization/templates.md).
