### ISSUE TITLE
Packagist install count

### ISSUE THREAD

**Issue by TheCelavi** [symfony2admingenerator/GeneratorBundle#308]
Is this real: https://packagist.org/packages/symfony2admingenerator/generator-bundle ? I am seeing 3 882 installs, I could bet my a** that it was more than that... Is this number correct?

**Comment by bobvandevijver** [comment]
I see the same, not sure why it is that much less nowadays. Maybe they use a new algorithm to determine the amount of downloads (in which the more effectively removed updates?). 

Not sure, but not an issue, so I will close this :) If you want to chat more about this, take a look at our [Gitter room](https://gitter.im/symfony2admingenerator/GeneratorBundle).
