### ISSUE TITLE
Support for new upcoming Symfony versions 3.3 and 4

### ISSUE THREAD

**Issue by TheCelavi** [symfony2admingenerator/GeneratorBundle#309]
Hello,

New SF versions are about to come very soon. With those versions, there will be support for bundleless applications. Twig 2 is also released.

This project seams to have little activity lately. So, what is the plan for future support? Is there going to be continuation of further development of this bundle?

**Comment by bobvandevijver** [comment]
Same as with the FormExtensionsbundle I'm afraid..  

(for others, see https://github.com/symfony2admingenerator/FormExtensionsBundle/issues/77)

**Comment by TheCelavi** [comment]
Hm.... too bad, project is much better then SonataAdminBundle, per example... I have worked with both admin generators, Sonata is not nearly easily customizable as this one... but Sonata seams to have more "advertising" efforts invested in it... 

Ok, so, it would be too bad to leave this project to die. How can we help? How about to start discussion on how to implement support for SF 3.3 / SF 4?

**Comment by bobvandevijver** [comment]
When I read the articles about SF4, it seems like there is only a best practice to use bundle-less applications, but I guess that the original bundle structure would still be functional (but it might be I'm wrong).

Guess that if we want to support actual bundle-less applications, we should completely revisit the generation structure. That might be a cumbersome task...

**Comment by TheCelavi** [comment]
Yes, it will be a lot of work to do. In order for this project to still be in the game is to support new, upcoming changes. 

New improvements are required as well, such as speed of code generation, some optimizations and what now... Maybe even some feature depreciations, like support for Propel? 

I am going to close this issue for now - just note that I am willing to help with working/maintaining this project.

**Comment by loostro** [comment]
@bobvandevijver is Propel currently maintained by anyone from the core team? while Doctrine ORM/ODM APIs have much in common and it's not a big leap to support the latter, Propel is whole diffrent game

I'd seriously consider @TheCelavi proposition of feature deprecation, if this bundle is to move forward.

**Comment by bobvandevijver** [comment]
I believe only @cedriclombardot is using propel, and it looks like he's working on Propel 2 support (https://github.com/symfony2admingenerator/GeneratorBundle/pull/307). 

However, I would not mind dropping support.
