### ISSUE TITLE
filters problem

### ISSUE THREAD

**Issue by snuffer82** [symfony2admingenerator/GeneratorBundle#319]
hi!
I have a problem setting up a numeric field as a filter.

` {% block list_filters_field_datagg %}
        {% if (true) %}
             <div class="list-filters-field-datagg list-filters-type-symfony\component\form\extension\core\type\numbertype">
                                {% block list_filters_field_datagg_content %}
                                {{ form_row(form['dataGg']) }}
    {% endblock list_filters_field_datagg_content %}`

if I configure this field as a filter (or any other numeric field) I get this error:
![filter_error](https://user-images.githubusercontent.com/17122286/35856200-8e7c1556-0b35-11e8-98e2-2f594638e4e3.jpeg)

ps. I have no problems with texttype or entitytype, only with numbertype

How can I solve the problem?
thanks
Paolo

**Comment by tobias-93** [comment]
Hi @snuffer82,

The answer is shown in the error: you must configure the scale parameter correctly (so it should not be an empty string).
You can do this in the generator.yml where you define the filter options.
If you don't know what I mean, could you submit your generator.yml so I can have a look what's happening?

Thanks

**Comment by snuffer82** [comment]
hi, 
thanks for quick response. This is my generator.yml

`
generator: admingenerator.generator.doctrine
params:
    model: AppBundle\Entity\TSchedaGenerale
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~

    fields:
      dataGg:
        label: Data (gg)
      dataMm:
        label: Data (mm) 
      dataAa:
        label:  Data (aaaa) 
      idTipoEvento:
        label: Tipo Segnalazione
        sortOn:  idTipoEvento.idTipoEvento
      codiceSegnalazione:
        label: Codice Segnalazione/Animale 
      numeroEsemplari:
        label: Numero Esemplari 
      rilevatore:
        label: Rilevatore  
      note:
        label: Note
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Elenco Segnalazioni
            display: [codiceSegnalazione, dataGg, dataMm, dataAa, idTipoEvento, ordine, species]
            actions:
                new: ~
                excel: ~
            object_actions:
                edit: ~
                delete: ~
                excel: ~
                show: ~
            batch_actions:
                delete: ~
            filters: [codiceSegnalazione, dataGg, idTipoEvento, phylum, ordine, species, infraspecies, nazione, regione, provincia, comune, citta, cap ]        
            filtersMode: modal `

**Comment by tobias-93** [comment]
Thank you for reporting, apparently this error has been present for a long time!
I've just fixed it in the latest release, you can use version 2.4.2.
Please let me know if the issue is resolved.

**Comment by snuffer82** [comment]
I've replace "DoctrineFieldGuesser.php" with the new version.
Now  the problem is solved!
Thanks a lot
p.
