### ISSUE TITLE
embed form

### ISSUE THREAD

**Issue by snuffer82** [symfony2admingenerator/GeneratorBundle#322]
Hi, 
How can I use embed forms (es. s2a_collection_table)? I use symfony 3.3 - doctrine.
I installed FormExtensionsBundle but collection type doesn't work properly
I try to use also: https://symfony-collection.fuz.org/symfony3/
but I don't understand how to integrate with admin2generatorbundle...

thanks a lot
Paolo

**Comment by bobvandevijver** [comment]
If you want to use the Symfony Collection (I also use that one in a project), I can only recommend you to create your own collection form type, as you will probably require the flexibility of the form type and view. You can of course use the collection types in here as a starting point.

**Comment by snuffer82** [comment]
Thanks a lot. Could you send me an example of the code you used?
It would help me a lot to understand how to do it. Thank you so much for the suggestion
