### ISSUE TITLE
Deprecated the security.context service

### ISSUE THREAD

**Issue by ksn135** [symfony2admingenerator/GeneratorBundle#72]
It's NOT deprecated right now, but may be we should prepare for this BC early, if we already based on version 2.6. I'm talking about many setSecurityContext function calls in code that will become obsolete.
Quote:
```
// Symfony 2.5
$user = $this->get('security.context')->getToken()->getUser();
// Symfony 2.6
$user = $this->get('security.token_storage')->getToken()->getUser();

// Symfony 2.5
if (false === $this->get('security.context')->isGranted('ROLE_ADMIN')) { ... }
// Symfony 2.6
if (false === $this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) { ... }
```
Source: http://symfony.com/blog/new-in-symfony-2-6-security-component-improvements

**Comment by loostro** [comment]
It seems 2.7 will be out on May 2015. I suggest when it's out we bump the requerements to sf 2.7
