### ISSUE TITLE
Filtering on associated fields

### ISSUE THREAD

**Issue by loostro** [symfony2admingenerator/GeneratorBundle#73]
As reported by @calvera in [commit#2373398](https://github.com/symfony2admingenerator/GeneratorBundle/commit/237339872887bb0b46c5d20dc7d95d8049b7d125#commitcomment-9005815), the `getAllFields` does not return associations, which makes int improssible (with the current implementation) to filter by associations.

**Comment by loostro** [comment]
@sescandell I think this can be closed, as #96 should fix it, right?

**Comment by sescandell** [comment]
Yes it should
