### ISSUE TITLE
credentials in field context

### ISSUE THREAD

**Issue by lucarnu** [symfony2admingenerator/GeneratorBundle#82]
Hi!

Actually I want to use credentials in field context:
```
  fields:
    myField:
      credentials: 'hasRole("ROLE_USER")'
```

After implementation of

```
params:
    fields:
        username:
            credentials: 'hasRole("ROLE_ADMIN")'
            label:            admin.user.fields.username

```
 every try gives an error:

```
Twig_Error_Runtime in classes.php line 4696: 
An exception has been thrown during the rendering of a template 
("Could not set option "credentials" on "username" column in "User" list builder.")
 in "ListBuilderAction.php.twig" at line 10.
```

After research, it seems to me, that field driven usage of credentials not is implemented. 
Do I am wrong?

If not, I like to think ahead:

Groups can be assigned to a field. So my idea would be to define groups in configuration file like:

```
params:
    groups:
        Admin:
            credentials: 'hasRole("ROLE_ADMIN")'
        User:
            credentials: 'hasRole("ROLE_USER")'
```
with usage

```
params:
    fields:
        username:
            groups:           ["User", "Admin"]
            label:            admin.user.fields.username
```

So in this case we need to change the getGroups method on EditController/NewController/ShowController like this:
``` EditBuilderAction.php.twig ```
```
    /**
     * Get groups.
     *
     * @param \{{ model }} ${{ builder.ModelClass }}
     * @return array
     */
    protected function getGroups(\{{ model }} ${{ builder.ModelClass }})
    {

        {% if true == builder.getVariable("groups") %}
        //ensure that it is not empty
        $groups = array("GROUPS_ENABLED");
            {% for key, group in builder.getVariable("groups") %}
                {% if group.credentials is defined %}

        if ($this->evaluate('{{group.credentials}}', ${{ builder.ModelClass }})) {
            $groups[] = "{{key}}";
        }

                {% else %}

        $groups[] = "{{key}}";

                {% endif %}
            {% endfor %}
        {% else %}
        $groups = array();
        {% endif %}

        return $groups;
    }
```

This would produce:
``` ~\EditController.php ```
```
    protected function getGroups(UserBundle\Entity\User $User)
    { 
        $groups = array("GROUPS_ENABLED");
                            
        if ($this->evaluate('hasRole("ROLE_ADMIN")', $User)) {
            $groups[] = "Admin";
        }
                                           
        if ($this->evaluate('hasRole("ROLE_USER")', $User)) {
            $groups[] = "User";
        }
                                    
        return $groups;
    }

```

What do you think about that?

**Comment by sescandell** [comment]
Hi @lucarnu 

 > After research, it seems to me, that field driven usage of credentials not is implemented. 
Do I am wrong?

No, you're not. Credentials term have been replaced by groups one for fields... and it's actually the same as what you propose. The only difference is that, for now, we let up to the developper to implement is own logic to create the `groups` value.

Your proposition might work, and like it, I think it could be usefull. I also wanted to improve that part (Groups management) but using more something like a service than code generation. I was more thinking about something like the `Options` class for forms. I would prefer to have a "centralized" object for groups value creation than dedicated code in all controllers. It would be usefull for forms too if this object is "centralized" (and easier to tweak it, adding cache and so on). What do you think about this approch?

Would you be able to push a PR for that?

**Comment by loostro** [comment]
I like the idea to move that part outside of controller. Slim controllers are more readable.

**Comment by lucarnu** [comment]
Hi @sescandell ,

I agree to this approach. It's cleaner, I suppose.
Ok, in this case I would implement this approach. 

So we could discuss my implementation with the next PR! :)

**Comment by loostro** [comment]
@lucarnu join our [gitter chat](https://gitter.im/symfony2admingenerator/GeneratorBundle) if you need to discuss PRs or just want to chat :)

**Comment by loostro** [comment]
@sescandell I think this can be closed as #96 implements this?

**Comment by sescandell** [comment]
Yes, but we also talked about improving Groups manager in this topic.
Don't know if you prefer to open a dedicated issue or stay on that one

**Comment by loostro** [comment]
OK, lets keep it open.
