### ISSUE TITLE
Scrutinizer keeps failing, any idea why?

### ISSUE THREAD

**Issue by loostro** [symfony2admingenerator/GeneratorBundle#92]
To me the config seems OK. I have no idea why it always fails on 41%. 

Any ideas? [example inspection](https://scrutinizer-ci.com/g/symfony2admingenerator/GeneratorBundle/inspections/14f4c5ba-6223-4b5c-aec7-cff4b406f2b1)

Just before it errors, it says "PHP Style analysis".

**Comment by sescandell** [comment]
Is there any way to se what's exactly running during this step?

**Comment by loostro** [comment]
You should be able to click "schedule inspection" and watch the process. While in progress, there is a message saying what is "analysed" now. Somewhere at 38-40% it sais "PHP Style analysis" and then the message is replaced with "Task failed" (and the % stops at 41).
