### ISSUE TITLE
Better caching on dev

### ISSUE THREAD

**Issue by matejvelikonja** [symfony2admingenerator/GeneratorBundle#95]
Everytime I do some changes in yml file of the generator, I have to manually delete the cache or I get the following exception.

```
Parse Error: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING)
```

I guess caching should detect if these files changed, and delete cache if that happens.

**Comment by sescandell** [comment]
I'm surprised about this issue.
If I'm not wrong, in dev mode, files are always parsed... Did you always had this issue, or this is something new?

**Comment by matejvelikonja** [comment]
This problem is occuring since the first day that I tried this bundle. Does it work normally with you? So for example you add a new field that is shown in a list and it works?

**Comment by sescandell** [comment]
Actually yes,

I just tested your scenario on the demo bundle adding the isPublished field to the posts' list and it worked.

**Comment by loostro** [comment]
I've never encountered this problem before. Could you try to isolate the problem? What exacly is in your `generator.yml`. What changes trigger this problem? Can share relevant code?

**Comment by matejvelikonja** [comment]
Since I opened this issue, the problem did not occur anymore, so for now I'm closing this issue.

**Comment by loostro** [comment]
@matejvelikonja sometimes, due to filesystem problems, cache may not be completely cleared even after running cache:clear command - I've experienced this on vagrant boxes with synced directories - they run `rm` command much slower and the `cache:clear` command returns to terminal before all cache is actually removed

then later, when symfony tries to generate new cache, it encounters leftovers from unclean `cache:clear` command.. the file may be locked, or directory may be not empty.. such edge cases usually disappear after manual cache removal OR another `cache:clear` command

Maybe you experienced something like this.

**Comment by matejvelikonja** [comment]
I'm reopening this again, since I started to happen again. Now even more regularly. I have to manually remove cache after every request, since the second request is always broken.
And yes, I am using vagrant. But I have tried also moving cache folder to the vagrant and not the NFS share. I thought that this would fix the issue, but it hasn't.

I have also find maybe related bug on JMSDiExtraBundle. https://github.com/schmittjoh/JMSDiExtraBundle/issues/184

Not really sure, what should I try next.

**Comment by loostro** [comment]
The problems you're experiencing are most likely not related to AdminGenerator bundle. There are many bundles that can cause problems with cache. I'd start by double-checking all JMS/DiExtraBundle and JMS/SecurityExtraBundle annotations and/or JMS/SeriallizerBundle (if you use it) mappings.

**Comment by ksn135** [comment]
Same issue happens to me sometimes. Can't catch it.
But I can confirm that it's related to JMS/DiExtraBundle (it adds extra slash before class name, because there is no vendor namespace) and it happens ONLY when I use AppBundle without vendor namespace as suggested in best practices.

**Comment by matejvelikonja** [comment]
I've fix this in JMS DI Bundle. Do you have latests version?
https://github.com/schmittjoh/JMSDiExtraBundle/pull/197

**Comment by ksn135** [comment]
Well, update to ```dev-master```. We'll see results. Thanks!
