### ISSUE TITLE
Image in the Entity

### ISSUE THREAD

**Issue by peric** [symfony2admingenerator/GeneratorBundle#97]
What is the best way to show/edit/add image from the entity? I was trying to do it in the same way as it's shown in the demo page, but just the input type "text" was rendered for the image - there was no uploader or whatsoever. Is this even supported/possible?

**Comment by loostro** [comment]
Use `VichUploaderBundle` to manage file upload/injection into entity field.
Use `FormExtensionsBundle` `s2a_single_upload` or `s2a_collection_upload` to manage single/multiple images.
Use `LiipImagineBundle` to apply filters (like crop, resize) to images.

**Comment by loostro** [comment]
See [form extensions bundle documentation](https://github.com/symfony2admingenerator/FormExtensionsBundle/blob/master/Resources/doc/documentation.md) for more info.

**Comment by peric** [comment]
Thanks. I'll try that.

**Comment by loostro** [comment]
For future visitors, see [this gist example](https://gist.github.com/loostro/5497377f22956766948c)
