### ISSUE TITLE
Should scope groups be inline?

### ISSUE THREAD

**Issue by loostro** [symfony2admingenerator/GeneratorBundle#98]
In legacy bundle, the scope groups were in one row (if enought width was avaliable).

This is how it looks on current master:
![inline-scopes](https://cloud.githubusercontent.com/assets/1419884/6906754/f510ded2-d730-11e4-9730-730a41eeaaa4.png)

Should we change that? @sescandell 
I can make a PR.

**Comment by loostro** [comment]
The proposed (inline) would like like this:
![f510ded2-d730-11e4-9730-730a41eeaaa4](https://cloud.githubusercontent.com/assets/1419884/7088654/f0ef2ef4-df95-11e4-9068-5cd2f3351746.png)

**Comment by sescandell** [comment]
I think inline is better: less space is used.

**Comment by bobvandevijver** [comment]
I agree, less space is better. Furthermore, you probably wont have more than 2 or 3 of those scopes (I currently use 1 as maximum).

However, take care that whenever more are used, the newline is done nicely and not such that for example the reset is right on the top line, while the two actual scope buttons are left in the second line. 

:+1:
